In [1]:
# This R environment comes with many helpful analytics packages installed
# It is defined by the kaggle/rstats Docker image: https://github.com/kaggle/docker-rstats
# For example, here's a helpful package to load

library(tidyverse) # metapackage of all tidyverse packages

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

list.files(path = "../input")

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

[1] "fitbit"

# **About the Company**

Bellabeat is a high – tech company that manufactures health – focused smart products. They offer different smart devices that collect data on activity, sleep, stress, and reproductive health to empower women with knowledge about their own health and habits.

The main focus of this case is to analyze smart devices fitness data and determine how it could help unlock new growth opportunities for Bellabeat. We will focus on one of Bellabeat’s products: Bellabeat app.

The Bellabeat app provides users with health data related to their activity, sleep, stress, menstrual cycle, and mindfulness habits. This data can help users better understand their current habits and make healthy decisions. The Bellabeat app connects to their line of smart wellness products.

Questions for the analysis:

What are some trends in smart device usage?
How could these trends apply to Bellabeat customers?
How could these trends help influence Bellabeat marketing strategy?

# **1. Ask Phase**

## **1.1 Business task**

Identify trends in how consumers use non – Bellabeat smart devices to apply insights into Bellabeat’s marketing strategy.

## **1.2 Key stakeholders**

Urška Sršen - Bellabeat cofounder and Chief Creative Officer.
Sando Mur - Bellabeat cofounder and key member of Bellabeat executive team.
Bellabeat Marketing Analytics team.

# **2. Prepare Phase**

## **2.1 Dataset used**

The data source for our case study is FitBit Fitness Tracker Data. This dataset is stored in Kaggle and was made available through Mobius.

## **2.2 Accessibility and privacy of data**

Verifying the metadata of our dataset we can confirm it is open-source. The owner has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighbouring rights, to the extent allowed by law. You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission.

## **2.3 Information about our dataset**

This dataset is generated by respondents to a distributed survey via Amazon Mechanical Turk between 04.11.2016 - 05.12.2016. Thirty eligible Fitbit users consented to the submission of personal tracker data, including minute-level output for physical activity, heart rate, and sleep monitoring. Variation between output represents use of different types of Fitbit trackers and individual tracking behaviours / preferences.

## **2.4 Data organisation and verification**

There are 18 CSV documents represent different quantitative data tracked by Fitbit. The data is considered long as each row is one time point per subject, so each subject will have data in multiple rows. Every user has unique ID and different rows as data is tracked by date and time. 

## **2.5 Data credibility and integrity**

Due to the limitation of size (30 users) and no any demographic information we could encounter a sampling bias. We are not sure if the sample is representative of the population as a whole. Another problem we would encounter is that the dataset is not current and also the time limitation of the survey. That is why we will give our case study an operational approach.

# **3. Process Phase**

I will focus my analysis in R due to the accessibility, amount of data and to be able to create data visualization to share my results with stakeholders.

## **3.1 Installing packages and opening libraries**

I am going to use following packages:

In [2]:
library(tidyverse)
library(here)
library(skimr)
library(janitor)
library(lubridate)
library(ggplot2)

here() starts at /kaggle/working


Attaching package: ‘janitor’


The following objects are masked from ‘package:stats’:

    chisq.test, fisher.test

## **3.2 Importing datasets**

Knowing the datasets we have, I am going to upload the datasets that will help me answer our business task. On our analysis I will focus on the following datasets:

Daily_activity
Daily_sleep
Hourly_steps

In [3]:
daily_activity <- read.csv("/kaggle/input/fitbit/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv")
daily_sleep <- read.csv("/kaggle/input/fitbit/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/sleepDay_merged.csv")
hourly_steps <- read.csv("/kaggle/input/fitbit/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/hourlySteps_merged.csv")

## **3.3 Preview datasets**

Preview selected data frames and check the summary of each column.

In [4]:
head(daily_activity)
str(daily_activity)

head(daily_sleep)
str(daily_sleep)

head(hourly_steps)
str(hourly_steps)

  Id         ActivityDate TotalSteps TotalDistance TrackerDistance
1 1503960366 4/12/2016    13162      8.50          8.50
2 1503960366 4/13/2016    10735      6.97          6.97
3 1503960366 4/14/2016    10460      6.74          6.74
4 1503960366 4/15/2016     9762      6.28          6.28
5 1503960366 4/16/2016    12669      8.16          8.16
6 1503960366 4/17/2016     9705      6.48          6.48
  LoggedActivitiesDistance VeryActiveDistance ModeratelyActiveDistance
1 0                        1.88               0.55
2 0                        1.57               0.69
3 0                        2.44               0.40
4 0                        2.14               1.26
5 0                        2.71               0.41
6 0                        3.19               0.78
  LightActiveDistance SedentaryActiveDistance VeryActiveMinutes
1 6.06                0                       25
2 4.71                0                       21
3 3.91                0                       30
4 2.83                0                       29
5 5.04                0                       36
6 2.51                0                       38
  FairlyActiveMinutes LightlyActiveMinutes SedentaryMinutes Calories
1 13                  328                   728             1985
2 19                  217                   776             1797
3 11                  181                  1218             1776
4 34                  209                   726             1745
5 10                  221                   773             1863
6 20                  164                   539             1728

'data.frame':	940 obs. of  15 variables:
 $ Id                      : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ ActivityDate            : chr  "4/12/2016" "4/13/2016" "4/14/2016" "4/15/2016" ...
 $ TotalSteps              : int  13162 10735 10460 9762 12669 9705 13019 15506 10544 9819 ...
 $ TotalDistance           : num  8.5 6.97 6.74 6.28 8.16 ...
 $ TrackerDistance         : num  8.5 6.97 6.74 6.28 8.16 ...
 $ LoggedActivitiesDistance: num  0 0 0 0 0 0 0 0 0 0 ...
 $ VeryActiveDistance      : num  1.88 1.57 2.44 2.14 2.71 ...
 $ ModeratelyActiveDistance: num  0.55 0.69 0.4 1.26 0.41 ...
 $ LightActiveDistance     : num  6.06 4.71 3.91 2.83 5.04 ...
 $ SedentaryActiveDistance : num  0 0 0 0 0 0 0 0 0 0 ...
 $ VeryActiveMinutes       : int  25 21 30 29 36 38 42 50 28 19 ...
 $ FairlyActiveMinutes     : int  13 19 11 34 10 20 16 31 12 8 ...
 $ LightlyActiveMinutes    : int  328 217 181 209 221 164 233 264 205 211 ...
 $ SedentaryMinutes        : int  728 776 1218 726 773 539 1149 775 818 838 ...
 $ Calories                : int  1985 1797 1776 1745 1863 1728 1921 2035 1786 1775 ...

  Id         SleepDay              TotalSleepRecords TotalMinutesAsleep
1 1503960366 4/12/2016 12:00:00 AM 1                 327
2 1503960366 4/13/2016 12:00:00 AM 2                 384
3 1503960366 4/15/2016 12:00:00 AM 1                 412
4 1503960366 4/16/2016 12:00:00 AM 2                 340
5 1503960366 4/17/2016 12:00:00 AM 1                 700
6 1503960366 4/19/2016 12:00:00 AM 1                 304
  TotalTimeInBed
1 346
2 407
3 442
4 367
5 712
6 320

'data.frame':	413 obs. of  5 variables:
 $ Id                : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ SleepDay          : chr  "4/12/2016 12:00:00 AM" "4/13/2016 12:00:00 AM" "4/15/2016 12:00:00 AM" "4/16/2016 12:00:00 AM" ...
 $ TotalSleepRecords : int  1 2 1 2 1 1 1 1 1 1 ...
 $ TotalMinutesAsleep: int  327 384 412 340 700 304 360 325 361 430 ...
 $ TotalTimeInBed    : int  346 407 442 367 712 320 377 364 384 449 ...

  Id         ActivityHour          StepTotal
1 1503960366 4/12/2016 12:00:00 AM 373
2 1503960366 4/12/2016 1:00:00 AM  160
3 1503960366 4/12/2016 2:00:00 AM  151
4 1503960366 4/12/2016 3:00:00 AM    0
5 1503960366 4/12/2016 4:00:00 AM    0
6 1503960366 4/12/2016 5:00:00 AM    0

'data.frame':	22099 obs. of  3 variables:
 $ Id          : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ ActivityHour: chr  "4/12/2016 12:00:00 AM" "4/12/2016 1:00:00 AM" "4/12/2016 2:00:00 AM" "4/12/2016 3:00:00 AM" ...
 $ StepTotal   : int  373 160 151 0 0 0 0 0 250 1864 ...

## **3.4 Cleaning and formatting**

Now that I know more about the data structures I will process them to look for any errors and inconsistencies.

### 3.4.1 Veryfing number of users 

Before I will continue with the cleaning I want to make sure how many unique users are per data frame. Even though 30 is the minimal sample size I will still keep the sleep dataset for practice only.

In [5]:
n_unique(daily_activity$Id)
n_unique(daily_sleep$Id)
n_unique(hourly_steps$Id)

[1] 33

[1] 24

[1] 33

### 3.4.2 Duplicates

I will now look for duplicates

In [6]:
sum(duplicated(daily_activity))
sum(duplicated(daily_sleep))
sum(duplicated(hourly_steps))

[1] 0

[1] 3

[1] 0

### 3.4.3 Removing duplicates and N/A

There are 457 obs. in daily_activity, 413 obs. in daily_sleep, and 24084 obs. in hourly_steps  (before removing duplicates and N/A).

In [7]:
daily_activity <- daily_activity %>%
  distinct() %>%
  drop_na()

daily_sleep <- daily_sleep %>%
  distinct() %>%
  drop_na()

hourly_steps <- hourly_steps %>%
  distinct() %>%
  drop_na()

Veryfing the duplicates and N/A have been removed.

In [8]:
sum(duplicated(daily_sleep))

[1] 0

Duplicates have been removed from daily_sleep dataset.

In [9]:
str(daily_activity)

str(daily_sleep)

str(hourly_steps)

'data.frame':	940 obs. of  15 variables:
 $ Id                      : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ ActivityDate            : chr  "4/12/2016" "4/13/2016" "4/14/2016" "4/15/2016" ...
 $ TotalSteps              : int  13162 10735 10460 9762 12669 9705 13019 15506 10544 9819 ...
 $ TotalDistance           : num  8.5 6.97 6.74 6.28 8.16 ...
 $ TrackerDistance         : num  8.5 6.97 6.74 6.28 8.16 ...
 $ LoggedActivitiesDistance: num  0 0 0 0 0 0 0 0 0 0 ...
 $ VeryActiveDistance      : num  1.88 1.57 2.44 2.14 2.71 ...
 $ ModeratelyActiveDistance: num  0.55 0.69 0.4 1.26 0.41 ...
 $ LightActiveDistance     : num  6.06 4.71 3.91 2.83 5.04 ...
 $ SedentaryActiveDistance : num  0 0 0 0 0 0 0 0 0 0 ...
 $ VeryActiveMinutes       : int  25 21 30 29 36 38 42 50 28 19 ...
 $ FairlyActiveMinutes     : int  13 19 11 34 10 20 16 31 12 8 ...
 $ LightlyActiveMinutes    : int  328 217 181 209 221 164 233 264 205 211 ...
 $ SedentaryMinutes        : int  728 776 1218 726 773 539 1149 775 818 838 ...
 $ Calories                : int  1985 1797 1776 1745 1863 1728 1921 2035 1786 1775 ...
'data.frame':	410 obs. of  5 variables:
 $ Id                : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ SleepDay          : chr  "4/12/2016 12:00:00 AM" "4/13/2016 12:00:00 AM" "4/15/2016 12:00:00 AM" "4/16/2016 12:00:00 AM" ...
 $ TotalSleepRecords : int  1 2 1 2 1 1 1 1 1 1 ...
 $ TotalMinutesAsleep: int  327 384 412 340 700 304 360 325 361 430 ...
 $ TotalTimeInBed    : int  346 407 442 367 712 320 377 364 384 449 ...
'data.frame':	22099 obs. of  3 variables:
 $ Id          : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ ActivityHour: chr  "4/12/2016 12:00:00 AM" "4/12/2016 1:00:00 AM" "4/12/2016 2:00:00 AM" "4/12/2016 3:00:00 AM" ...
 $ StepTotal   : int  373 160 151 0 0 0 0 0 250 1864 ...

It looks like there was no any N/A observations. Daily_sleep has now 410 observations.

### 3.4.4 Clean and rename columns

I would like to make sure that all column names use same right syntax and format in all datasets as they will be merged later on.

Changing the format of all columns to lower case.

In [10]:
clean_names(daily_activity)
daily_activity<- rename_with(daily_activity, tolower)

clean_names(daily_sleep)
daily_sleep <- rename_with(daily_sleep, tolower)

clean_names(hourly_steps)
hourly_steps <- rename_with(hourly_steps, tolower)

    id         activity_date total_steps total_distance tracker_distance
1   1503960366 4/12/2016     13162        8.50           8.50
2   1503960366 4/13/2016     10735        6.97           6.97
3   1503960366 4/14/2016     10460        6.74           6.74
4   1503960366 4/15/2016      9762        6.28           6.28
5   1503960366 4/16/2016     12669        8.16           8.16
6   1503960366 4/17/2016      9705        6.48           6.48
7   1503960366 4/18/2016     13019        8.59           8.59
8   1503960366 4/19/2016     15506        9.88           9.88
9   1503960366 4/20/2016     10544        6.68           6.68
10  1503960366 4/21/2016      9819        6.34           6.34
11  1503960366 4/22/2016     12764        8.13           8.13
12  1503960366 4/23/2016     14371        9.04           9.04
13  1503960366 4/24/2016     10039        6.41           6.41
14  1503960366 4/25/2016     15355        9.80           9.80
15  1503960366 4/26/2016     13755        8.79           8.79
16  1503960366 4/27/2016     18134       12.21          12.21
17  1503960366 4/28/2016     13154        8.53           8.53
18  1503960366 4/29/2016     11181        7.15           7.15
19  1503960366 4/30/2016     14673        9.25           9.25
20  1503960366 5/1/2016      10602        6.81           6.81
21  1503960366 5/2/2016      14727        9.71           9.71
22  1503960366 5/3/2016      15103        9.66           9.66
23  1503960366 5/4/2016      11100        7.15           7.15
24  1503960366 5/5/2016      14070        8.90           8.90
25  1503960366 5/6/2016      12159        8.03           8.03
26  1503960366 5/7/2016      11992        7.71           7.71
27  1503960366 5/8/2016      10060        6.58           6.58
28  1503960366 5/9/2016      12022        7.72           7.72
29  1503960366 5/10/2016     12207        7.77           7.77
30  1503960366 5/11/2016     12770        8.13           8.13
⋮   ⋮          ⋮             ⋮           ⋮              ⋮
911 8877689391 4/13/2016     15337        9.58           9.58
912 8877689391 4/14/2016     21129       18.98          18.98
913 8877689391 4/15/2016     13422        7.17           7.17
914 8877689391 4/16/2016     29326       25.29          25.29
915 8877689391 4/17/2016     15118        8.87           8.87
916 8877689391 4/18/2016     11423        8.67           8.67
917 8877689391 4/19/2016     18785       17.40          17.40
918 8877689391 4/20/2016     19948       18.11          18.11
919 8877689391 4/21/2016     19377       17.62          17.62
920 8877689391 4/22/2016     18258       16.31          16.31
921 8877689391 4/23/2016     11200        7.43           7.43
922 8877689391 4/24/2016     16674       15.74          15.74
923 8877689391 4/25/2016     12986        8.74           8.74
924 8877689391 4/26/2016     11101        8.43           8.43
925 8877689391 4/27/2016     23629       20.65          20.65
926 8877689391 4/28/2016     14890       11.30          11.30
927 8877689391 4/29/2016      9733        7.39           7.39
928 8877689391 4/30/2016     27745       26.72          26.72
929 8877689391 5/1/2016      10930        8.32           8.32
930 8877689391 5/2/2016       4790        3.64           3.64
931 8877689391 5/3/2016      10818        8.21           8.21
932 8877689391 5/4/2016      18193       16.30          16.30
933 8877689391 5/5/2016      14055       10.67          10.67
934 8877689391 5/6/2016      21727       19.34          19.34
935 8877689391 5/7/2016      12332        8.13           8.13
936 8877689391 5/8/2016      10686        8.11           8.11
937 8877689391 5/9/2016      20226       18.25          18.25
938 8877689391 5/10/2016     10733        8.15           8.15
939 8877689391 5/11/2016     21420       19.56          19.56
940 8877689391 5/12/2016      8064        6.12           6.12
    logged_activities_distance very_active_distance moderately_active_distance
1   0                          1.88                 0.55
2   0                          1.57                 0.69
3   0                          2.44                 0.40
4   0                          2.14                 1.26
5   0                          2.71                 0.41
6   0                          3.19                 0.78
7   0                          3.25                 0.64
8   0                          3.53                 1.32
9   0                          1.96                 0.48
10  0                          1.34                 0.35
11  0                          4.76                 1.12
12  0                          2.81                 0.87
13  0                          2.92                 0.21
14  0                          5.29                 0.57
15  0                          2.33                 0.92
16  0                          6.40                 0.41
17  0                          3.54                 1.16
18  0                          1.06                 0.50
19  0                          3.56                 1.42
20  0                          2.29                 1.60
21  0                          3.21                 0.57
22  0                          3.73                 1.05
23  0                          2.46                 0.87
24  0                          2.92                 1.08
25  0                          1.97                 0.25
26  0                          2.46                 2.12
27  0                          3.53                 0.32
28  0                          3.45                 0.53
29  0                          3.35                 1.16
30  0                          2.56                 1.01
⋮   ⋮                          ⋮                    ⋮
911 0                           3.55                0.38
912 0                          10.55                0.59
913 0                           0.05                0.05
914 0                          13.24                1.21
915 0                           0.00                0.07
916 0                           2.44                0.27
917 0                          12.15                0.18
918 0                          11.02                0.69
919 0                          12.29                0.42
920 0                          10.23                0.03
921 0                           0.00                0.00
922 0                          11.01                0.01
923 0                           2.37                0.07
924 0                           1.76                0.13
925 0                          13.07                0.44
926 0                           4.93                0.38
927 0                           1.38                0.17
928 0                          21.66                0.08
929 0                           3.13                0.57
930 0                           0.00                0.00
931 0                           1.39                0.10
932 0                          10.42                0.31
933 0                           5.46                0.82
934 0                          12.79                0.29
935 0                           0.08                0.96
936 0                           1.08                0.20
937 0                          11.10                0.80
938 0                           1.35                0.46
939 0                          13.22                0.41
940 0                           1.82                0.04
    light_active_distance sedentary_active_distance very_active_minutes
1   6.06                  0                         25
2   4.71                  0                         21
3   3.91                  0                         30
4   2.83                  0                         29
5   5.04                  0                         36
6   2.51                  0                         38
7   4.71                  0                         42
8   5.03                  0                         50
9   4.24                  0                         28
10  4.65                  0                         19
11  2.24                  0                         66
12  5.36                  0                         41
13  3.28                  0                         39
14  3.94                  0                         73
15  5.54                  0                         31
16  5.41                  0                         78
17  3.79                  0                         48
18  5.58                  0                         16
19  4.27                  0                         52
20  2.92                  0                         33
21  5.92                  0                         41
22  4.88                  0                         50
23  3.82                  0                         36
24  4.88                  0                         45
25  5.81                  0                         24
26  3.13                  0                         37
27  2.73                  0                         44
28  3.74                  0                         46
29  3.26                  0                         46
30  4.55                  0                         36
⋮   ⋮                     ⋮                         ⋮
911  5.64                 0.00                      108
912  7.75                 0.02                       68
913  7.01                 0.01                      106
914 10.71                 0.00                       94
915  8.79                 0.00                       58
916  5.94                 0.00                       29
917  5.03                 0.00                       82
918  6.34                 0.00                       73
919  4.89                 0.00                       82
920  5.97                 0.05                       61
921  7.40                 0.01                      102
922  4.69                 0.00                       64
923  6.27                 0.01                      113
924  6.50                 0.00                       22
925  7.10                 0.00                       93
926  5.97                 0.00                       58
927  5.79                 0.00                       18
928  4.93                 0.00                      124
929  4.57                 0.00                       36
930  3.56                 0.00                        0
931  6.67                 0.01                       19
932  5.53                 0.00                       66
933  4.37                 0.00                       67
934  6.16                 0.00                       96
935  6.99                 0.00                      105
936  6.80                 0.00                       17
937  6.24                 0.05                       73
938  6.28                 0.00                       18
939  5.89                 0.00                       88
940  4.25                 0.00                       23
    fairly_active_minutes lightly_active_minutes sedentary_minutes calories
1   13                    328                     728              1985
2   19                    217                     776              1797
3   11                    181                    1218              1776
4   34                    209                     726              1745
5   10                    221                     773              1863
6   20                    164                     539              1728
7   16                    233                    1149              1921
8   31                    264                     775              2035
9   12                    205                     818              1786
10   8                    211                     838              1775
11  27                    130                    1217              1827
12  21                    262                     732              1949
13   5                    238                     709              1788
14  14                    216                     814              2013
15  23                    279                     833              1970
16  11                    243                    1108              2159
17  28                    189                     782              1898
18  12                    243                     815              1837
19  34                    217                     712              1947
20  35                    246                     730              1820
21  15                    277                     798              2004
22  24                    254                     816              1990
23  22                    203                    1179              1819
24  24                    250                     857              1959
25   6                    289                     754              1896
26  46                    175                     833              1821
27   8                    203                     574              1740
28  11                    206                     835              1819
29  31                    214                     746              1859
30  23                    251                     669              1783
⋮   ⋮                     ⋮                      ⋮                 ⋮
911 18                    216                    1098              3566
912 13                    298                    1061              3793
913  1                    281                    1052              3934
914 29                    429                     888              4547
915 15                    307                    1060              3545
916  5                    191                    1215              2761
917 13                    214                    1131              3676
918 19                    225                    1123              3679
919 13                    226                    1119              3659
920  2                    236                    1141              3427
921  6                    300                    1032              3891
922  1                    227                    1148              3455
923  8                    218                    1101              3802
924  3                    258                    1157              2860
925  8                    235                    1104              3808
926  8                    231                    1143              3060
927  5                    210                    1207              2698
928  4                    223                    1089              4398
929 12                    166                    1226              2786
930  0                    105                    1335              2189
931  3                    229                    1189              2817
932  8                    212                    1154              3477
933 15                    188                    1170              3052
934 17                    232                    1095              4015
935 28                    271                    1036              4142
936  4                    245                    1174              2847
937 19                    217                    1131              3710
938 11                    224                    1187              2832
939 12                    213                    1127              3832
940  1                    137                     770              1849

    id         sleep_day             total_sleep_records total_minutes_asleep
1   1503960366 4/12/2016 12:00:00 AM 1                   327
2   1503960366 4/13/2016 12:00:00 AM 2                   384
3   1503960366 4/15/2016 12:00:00 AM 1                   412
4   1503960366 4/16/2016 12:00:00 AM 2                   340
5   1503960366 4/17/2016 12:00:00 AM 1                   700
6   1503960366 4/19/2016 12:00:00 AM 1                   304
7   1503960366 4/20/2016 12:00:00 AM 1                   360
8   1503960366 4/21/2016 12:00:00 AM 1                   325
9   1503960366 4/23/2016 12:00:00 AM 1                   361
10  1503960366 4/24/2016 12:00:00 AM 1                   430
11  1503960366 4/25/2016 12:00:00 AM 1                   277
12  1503960366 4/26/2016 12:00:00 AM 1                   245
13  1503960366 4/28/2016 12:00:00 AM 1                   366
14  1503960366 4/29/2016 12:00:00 AM 1                   341
15  1503960366 4/30/2016 12:00:00 AM 1                   404
16  1503960366 5/1/2016 12:00:00 AM  1                   369
17  1503960366 5/2/2016 12:00:00 AM  1                   277
18  1503960366 5/3/2016 12:00:00 AM  1                   273
19  1503960366 5/5/2016 12:00:00 AM  1                   247
20  1503960366 5/6/2016 12:00:00 AM  1                   334
21  1503960366 5/7/2016 12:00:00 AM  1                   331
22  1503960366 5/8/2016 12:00:00 AM  1                   594
23  1503960366 5/9/2016 12:00:00 AM  1                   338
24  1503960366 5/10/2016 12:00:00 AM 1                   383
25  1503960366 5/11/2016 12:00:00 AM 1                   285
26  1644430081 4/29/2016 12:00:00 AM 1                   119
27  1644430081 4/30/2016 12:00:00 AM 1                   124
28  1644430081 5/2/2016 12:00:00 AM  1                   796
29  1644430081 5/8/2016 12:00:00 AM  1                   137
30  1844505072 4/15/2016 12:00:00 AM 1                   644
⋮   ⋮          ⋮                     ⋮                   ⋮
381 8378563200 4/28/2016 12:00:00 AM 1                   506
382 8378563200 4/29/2016 12:00:00 AM 1                   527
383 8378563200 4/30/2016 12:00:00 AM 1                   468
384 8378563200 5/1/2016 12:00:00 AM  1                   475
385 8378563200 5/2/2016 12:00:00 AM  1                   351
386 8378563200 5/3/2016 12:00:00 AM  1                   405
387 8378563200 5/4/2016 12:00:00 AM  1                   441
388 8378563200 5/5/2016 12:00:00 AM  1                   381
389 8378563200 5/6/2016 12:00:00 AM  1                   323
390 8378563200 5/7/2016 12:00:00 AM  2                   459
391 8378563200 5/8/2016 12:00:00 AM  1                   545
392 8378563200 5/9/2016 12:00:00 AM  1                   359
393 8378563200 5/10/2016 12:00:00 AM 1                   342
394 8378563200 5/11/2016 12:00:00 AM 1                   368
395 8378563200 5/12/2016 12:00:00 AM 1                   496
396 8792009665 4/12/2016 12:00:00 AM 1                   458
397 8792009665 4/13/2016 12:00:00 AM 1                   531
398 8792009665 4/14/2016 12:00:00 AM 1                   486
399 8792009665 4/15/2016 12:00:00 AM 1                   363
400 8792009665 4/20/2016 12:00:00 AM 1                   528
401 8792009665 4/22/2016 12:00:00 AM 1                   391
402 8792009665 4/23/2016 12:00:00 AM 1                   339
403 8792009665 4/27/2016 12:00:00 AM 1                   423
404 8792009665 4/28/2016 12:00:00 AM 1                   402
405 8792009665 4/29/2016 12:00:00 AM 1                   398
406 8792009665 4/30/2016 12:00:00 AM 1                   343
407 8792009665 5/1/2016 12:00:00 AM  1                   503
408 8792009665 5/2/2016 12:00:00 AM  1                   415
409 8792009665 5/3/2016 12:00:00 AM  1                   516
410 8792009665 5/4/2016 12:00:00 AM  1                   439
    total_time_in_bed
1   346
2   407
3   442
4   367
5   712
6   320
7   377
8   364
9   384
10  449
11  323
12  274
13  393
14  354
15  425
16  396
17  309
18  296
19  264
20  367
21  349
22  611
23  342
24  403
25  306
26  127
27  142
28  961
29  154
30  961
⋮   ⋮
381 556
382 562
383 555
384 539
385 385
386 429
387 477
388 417
389 355
390 513
391 606
392 399
393 391
394 387
395 546
396 493
397 552
398 503
399 377
400 547
401 407
402 360
403 428
404 416
405 406
406 360
407 527
408 423
409 545
410 463

      id         activity_hour         step_total
1     1503960366 4/12/2016 12:00:00 AM  373
2     1503960366 4/12/2016 1:00:00 AM   160
3     1503960366 4/12/2016 2:00:00 AM   151
4     1503960366 4/12/2016 3:00:00 AM     0
5     1503960366 4/12/2016 4:00:00 AM     0
6     1503960366 4/12/2016 5:00:00 AM     0
7     1503960366 4/12/2016 6:00:00 AM     0
8     1503960366 4/12/2016 7:00:00 AM     0
9     1503960366 4/12/2016 8:00:00 AM   250
10    1503960366 4/12/2016 9:00:00 AM  1864
11    1503960366 4/12/2016 10:00:00 AM  676
12    1503960366 4/12/2016 11:00:00 AM  360
13    1503960366 4/12/2016 12:00:00 PM  253
14    1503960366 4/12/2016 1:00:00 PM   221
15    1503960366 4/12/2016 2:00:00 PM  1166
16    1503960366 4/12/2016 3:00:00 PM  2063
17    1503960366 4/12/2016 4:00:00 PM   344
18    1503960366 4/12/2016 5:00:00 PM   489
19    1503960366 4/12/2016 6:00:00 PM  1386
20    1503960366 4/12/2016 7:00:00 PM   558
21    1503960366 4/12/2016 8:00:00 PM  1733
22    1503960366 4/12/2016 9:00:00 PM   684
23    1503960366 4/12/2016 10:00:00 PM   89
24    1503960366 4/12/2016 11:00:00 PM  338
25    1503960366 4/13/2016 12:00:00 AM  144
26    1503960366 4/13/2016 1:00:00 AM     0
27    1503960366 4/13/2016 2:00:00 AM     0
28    1503960366 4/13/2016 3:00:00 AM    36
29    1503960366 4/13/2016 4:00:00 AM     0
30    1503960366 4/13/2016 5:00:00 AM     0
⋮     ⋮          ⋮                     ⋮
22070 8877689391 5/11/2016 9:00:00 AM   338
22071 8877689391 5/11/2016 10:00:00 AM  295
22072 8877689391 5/11/2016 11:00:00 AM  974
22073 8877689391 5/11/2016 12:00:00 PM 3929
22074 8877689391 5/11/2016 1:00:00 PM   481
22075 8877689391 5/11/2016 2:00:00 PM    37
22076 8877689391 5/11/2016 3:00:00 PM   416
22077 8877689391 5/11/2016 4:00:00 PM  2869
22078 8877689391 5/11/2016 5:00:00 PM  8357
22079 8877689391 5/11/2016 6:00:00 PM   920
22080 8877689391 5/11/2016 7:00:00 PM   408
22081 8877689391 5/11/2016 8:00:00 PM   633
22082 8877689391 5/11/2016 9:00:00 PM   228
22083 8877689391 5/11/2016 10:00:00 PM  109
22084 8877689391 5/11/2016 11:00:00 PM    0
22085 8877689391 5/12/2016 12:00:00 AM    0
22086 8877689391 5/12/2016 1:00:00 AM     0
22087 8877689391 5/12/2016 2:00:00 AM     0
22088 8877689391 5/12/2016 3:00:00 AM     0
22089 8877689391 5/12/2016 4:00:00 AM     0
22090 8877689391 5/12/2016 5:00:00 AM     0
22091 8877689391 5/12/2016 6:00:00 AM   254
22092 8877689391 5/12/2016 7:00:00 AM   574
22093 8877689391 5/12/2016 8:00:00 AM   765
22094 8877689391 5/12/2016 9:00:00 AM   164
22095 8877689391 5/12/2016 10:00:00 AM  514
22096 8877689391 5/12/2016 11:00:00 AM 1407
22097 8877689391 5/12/2016 12:00:00 PM 3135
22098 8877689391 5/12/2016 1:00:00 PM   307
22099 8877689391 5/12/2016 2:00:00 PM   457

### 3.4.5 Consistency of date and time columns

Since I am going to merge daily_activity and daily_sleep data frames I will focus on cleaning date - time format. As there is no need of the time data on daily_sleep it can be disregared, thus I am going to use as_date instead of as_datetime function.

In [11]:
daily_activity <- daily_activity %>%
  rename(date = activitydate) %>%
  mutate(date = as_date(date, format = "%m/%d/%Y"))

daily_sleep <- daily_sleep %>%
  rename(date = sleepday) %>%
  mutate(date = as_date(date,format ="%m/%d/%Y %I:%M:%S %p", tz=Sys.timezone()))

Warning message:
“There was 1 warning in `mutate()`.
ℹ In argument: `date = as_date(date, format = "%m/%d/%Y %I:%M:%S %p", tz =
  Sys.timezone())`.
Caused by warning:
! `tz` argument is ignored by `as_date()`”

Checking my cleaned datasets.

In [12]:
head(daily_activity)
head(daily_sleep)

str(daily_activity)
str(daily_sleep)

  id         date       totalsteps totaldistance trackerdistance
1 1503960366 2016-04-12 13162      8.50          8.50
2 1503960366 2016-04-13 10735      6.97          6.97
3 1503960366 2016-04-14 10460      6.74          6.74
4 1503960366 2016-04-15  9762      6.28          6.28
5 1503960366 2016-04-16 12669      8.16          8.16
6 1503960366 2016-04-17  9705      6.48          6.48
  loggedactivitiesdistance veryactivedistance moderatelyactivedistance
1 0                        1.88               0.55
2 0                        1.57               0.69
3 0                        2.44               0.40
4 0                        2.14               1.26
5 0                        2.71               0.41
6 0                        3.19               0.78
  lightactivedistance sedentaryactivedistance veryactiveminutes
1 6.06                0                       25
2 4.71                0                       21
3 3.91                0                       30
4 2.83                0                       29
5 5.04                0                       36
6 2.51                0                       38
  fairlyactiveminutes lightlyactiveminutes sedentaryminutes calories
1 13                  328                   728             1985
2 19                  217                   776             1797
3 11                  181                  1218             1776
4 34                  209                   726             1745
5 10                  221                   773             1863
6 20                  164                   539             1728

  id         date       totalsleeprecords totalminutesasleep totaltimeinbed
1 1503960366 2016-04-12 1                 327                346
2 1503960366 2016-04-13 2                 384                407
3 1503960366 2016-04-15 1                 412                442
4 1503960366 2016-04-16 2                 340                367
5 1503960366 2016-04-17 1                 700                712
6 1503960366 2016-04-19 1                 304                320

'data.frame':	940 obs. of  15 variables:
 $ id                      : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ date                    : Date, format: "2016-04-12" "2016-04-13" ...
 $ totalsteps              : int  13162 10735 10460 9762 12669 9705 13019 15506 10544 9819 ...
 $ totaldistance           : num  8.5 6.97 6.74 6.28 8.16 ...
 $ trackerdistance         : num  8.5 6.97 6.74 6.28 8.16 ...
 $ loggedactivitiesdistance: num  0 0 0 0 0 0 0 0 0 0 ...
 $ veryactivedistance      : num  1.88 1.57 2.44 2.14 2.71 ...
 $ moderatelyactivedistance: num  0.55 0.69 0.4 1.26 0.41 ...
 $ lightactivedistance     : num  6.06 4.71 3.91 2.83 5.04 ...
 $ sedentaryactivedistance : num  0 0 0 0 0 0 0 0 0 0 ...
 $ veryactiveminutes       : int  25 21 30 29 36 38 42 50 28 19 ...
 $ fairlyactiveminutes     : int  13 19 11 34 10 20 16 31 12 8 ...
 $ lightlyactiveminutes    : int  328 217 181 209 221 164 233 264 205 211 ...
 $ sedentaryminutes        : int  728 776 1218 726 773 539 1149 775 818 838 ...
 $ calories                : int  1985 1797 1776 1745 1863 1728 1921 2035 1786 1775 ...
'data.frame':	410 obs. of  5 variables:
 $ id                : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
 $ date              : Date, format: "2016-04-12" "2016-04-13" ...
 $ totalsleeprecords : int  1 2 1 2 1 1 1 1 1 1 ...
 $ totalminutesasleep: int  327 384 412 340 700 304 360 325 361 430 ...
 $ totaltimeinbed    : int  346 407 442 367 712 320 377 364 384 449 ...

For the hourly_steps dataset I will convert date string to date - time.

In [13]:
hourly_steps <- hourly_steps %>% 
  rename(date_time = activityhour) %>% 
  mutate(date_time = as.POSIXct(date_time,format ="%m/%d/%Y %I:%M:%S %p", tz=Sys.timezone()))

In [14]:
head(hourly_steps)

  id         date_time           steptotal
1 1503960366 2016-04-12 00:00:00 373
2 1503960366 2016-04-12 01:00:00 160
3 1503960366 2016-04-12 02:00:00 151
4 1503960366 2016-04-12 03:00:00   0
5 1503960366 2016-04-12 04:00:00   0
6 1503960366 2016-04-12 05:00:00   0

## **3.5 Merging datasets**

I am going to merge daily_activity and daily_sleep to see any correlation between variables by using id and date as their primary keys.

In [15]:
ls()

 [1] "auth"                      "daily_activity"
 [3] "daily_sleep"               "get_user_secret"
 [5] "GET_USER_SECRET_ENDPOINT"  "hourly_steps"
 [7] "KAGGLE_BASE_URL"           "KAGGLE_IAP_TOKEN"
 [9] "KAGGLE_USER_SECRETS_TOKEN" "TokenBigQueryKernel"

In [16]:
daily_activity_sleep <- merge(daily_activity, daily_sleep, by.x = c ("Id","ActivityDate"), by.y = c("Id", "SleepDay"))

glimpse(daily_activity_sleep)

ERROR: Error in fix.by(by.x, x): 'by' must specify uniquely valid columns

In [ ]:
daily_activity$ActivityDate <- as.Date(daily_activity$ActivityDate, format = "%m%d%Y")
daily_sleep$SleepDay <- as.Date(daily_sleep$SleepDay, format = "%m%d%Y %I:%M:%S %p")

In [ ]:
daily_activity_sleep <- merge(daily_activity, daily_sleep,by.x = c("Id", "ActivityDate"), by.y = c("Id", "SleepDay"))
nrow(daily_activity_sleep)

# **4. Analyse and share phase**

I am going to analyse trends of the users of smart devices and determine if that can help on BellaBeat's marketing strategy.

## **4.1 Type of users per activity level**

Since there is no any demographic variables in the sample I want to determine the type of users with the data I have. I can classify the users by activity considering the daily amount of steps. We can categorize users as follows:

Sedentary - Less than 5000 steps a day.
Lightly active - Between 5000 and 7499 steps a day.
Fairly active - Between 7500 and 9999 steps a day.
Very active - More than 10000 steps a day.
Classification has been made base on the following article: https://www.10000steps.org.au/articles/counting-steps/

First I will calculate the daily average steps, calories, and sleep by user.

In [ ]:
library(tidyverse)

In [ ]:
daily_average <- daily_activity_sleep %>%
  group_by(Id) %>%
  summarise(mean_daily_steps = mean(TotalSteps, na.rm = TRUE), mean_daily_calories = mean(Calories, na.rm = TRUE), mean_daily_sleep = mean(TotalMinutesAsleep, na.rm = TRUE), .groups = "drop")

head(daily_average)

I am going to create user_type data frame, with a new column user_type which will classify users by the daily average steps, I will use mutate function.

In [ ]:
user_type <- daily_average %>%
  mutate(user_type = case_when(
    mean_daily_steps < 5000 ~ "sedentary",
    mean_daily_steps >= 5000 & mean_daily_steps < 7500 ~ "lightly active", 
    mean_daily_steps >= 7500 & mean_daily_steps < 10000 ~ "fairly active", 
    mean_daily_steps >= 10000 ~ "very active"
  ))

head(user_type)
glimpse(user_type)

Now that we have a new column with the user type we will create a data frame with the percentage of each user type to better visualize them on a graph.

In [ ]:
user_type_percent <- user_type %>%
    count(user_type) %>%
    mutate(
        total_percent = n / sum(n),
        labels = scales::percent(total_percent))

  user_type_percent

Above we can see that users are fairly distributed by their activity considering the daily amount of steps. 

Visualisation below shows the findings.

In [ ]:
user_type_percent %>%
  ggplot(aes(x="",y=total_percent, fill=user_type)) +
  geom_bar(stat = "identity", width = 1)+
  coord_polar("y", start=0)+
  theme_minimal()+
  theme(axis.title.x= element_blank(),
        axis.title.y = element_blank(),
        panel.border = element_blank(), 
        panel.grid = element_blank(), 
        axis.ticks = element_blank(),
        axis.text.x = element_blank(),
        plot.title = element_text(hjust = 0.5, size=14, face = "bold")) +
  scale_fill_manual(values = c("#85e085","#e6e600", "#ffd480", "#ff8080")) +
  geom_text(aes(label = labels),
            position = position_stack(vjust = 0.5))+
  labs(title="User type distribution")

The pie chart shows the distribution of users by average daily step count. The largest group is fairly active users (33.3%), followed by sedentary users (29.2%). Very active users account for 20.8%, while lightly active users represent 16.7%. These findings suggest that users have different activity levels, which could help Bellabeat tailor its marketing messages to diffrent groups.